name: Clean UP Dev Experience with Microsoft DevBox Deployment 

permissions:
    id-token: write
    contents: write
    
# note
on:
  workflow_dispatch: # Manually trigger the workflow

env:
  location: "westus3"
  solutionName: "PetDx"
  devBoxResourceGroupName: "PetDx-rg"
  networkResourceGroupName: "PetDx-Network-rg"
  managementResourceGroupName: "PetDx-Management-rg"
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE20: true

jobs:    
    CleanUp:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Log in to Azure
              uses: azure/login@v2
              with:
                creds: ${{ secrets.AZURE_CREDENTIALS }}
              
            - name: Grant execute permissions to the script
              run: | 
                chmod +x ./src/deploy/bicep/bash/cleanUpPipeline.sh
                
      
            - name: Cleaning Up Azure Resources for ${{ env.solutionName }}
              run: ./src/deploy/bicep/bash/cleanUpPipeline.sh ${{ env.devBoxResourceGroupName }} ${{ env.networkResourceGroupName }} ${{ env.managementResourceGroupName }} ${{ env.location }} 'eShopPetBuilderRole' ${{ secrets.AZURE_CREDENTIALS.subscriptionId }} 